### PR TITLE
normalize InvalidRequest api

### PR DESCRIPTION
**Pull request by mcucchi9**
This PR normalizes InvalidRequest api.

### CODE REVIEW

**Review by EddyCMWF — APPROVED** [review]

**Review by malmans2 — APPROVED** [review]

**Comment by EddyCMWF** [comment]
Don't merge quite yet, I just spotted a potential problem

**Comment by EddyCMWF** [comment]
I went through all the instances of InvalidRequest and found this one where it looks like the input message could be a dictionary:
https://github.com/ecmwf-projects/cads-adaptors/blob/main/cads_adaptors/adaptors/cams_regional_fc/cams_regional_fc.py#L321

Would this be a problem?

**Comment by EddyCMWF** [comment]
Is this line okay with the change:
https://github.com/ecmwf-projects/cads-adaptors/blob/main/cads_adaptors/validation/enforce.py#L124

**Comment by EddyCMWF** [comment]
FYI, I am just double checking that this call to InvalidRequest will not be adversely effected

https://github.com/ecmwf-projects/cads-adaptors/blob/main/cads_adaptors/adaptors/cams_regional_fc/cams_regional_fc.py#L321

**Comment by EddyCMWF** [comment]
Ignore my previous comments, I have since discovered that Python exceptions can handle multiple types of input

**Pull request merged**
